# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1952cc2556c34cf2338979c782325e35c5c25ccf83823a70a59f06f89e63a6963fd348f4bce95b4ad780d01ad4703dc97ad465c0afaa83aa1d57e43069e48ac1

test:
  secret_key_base: ba5bef34070c7575197d8f03e1a990d73e163643b51a3a8a32b114400bb0cd017b294d0a07415660a1138d35cbddd4fdeb11b70fe713a590e38d89e1cc80b39a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
